### ISSUE TITLE
Cannot build some of the drivers after the VS 16.10 update

### ISSUE THREAD

**Issue by 527395632** [raspberrypi/windows-drivers#31]
Hello, I'm a beginner. Today, when I tried to compile the driver, I found that there were some errors in the compilation process of some drivers, which could not be solved. I hope I can get help from big brother here（ If you send it in the wrong place, please forgive me

The error message is as follows: (Build Error Driver Project List)
1：rpiq
2：SerPL011
3：vchiq
4：vchiq_arm_kern
5：vcos_win32_kern
6：vcos_win32_kern_generic
![image](https://user-images.githubusercontent.com/20411721/120280140-e4662500-c2e9-11eb-90e9-dbcf1a3f8e2b.png)

"rpiq" and "SerPL011" driver project：I also disable the 'Spectre' of 'rpiq & SerPL011', However, other errors are displayed after disabling. This error should be an error during link.
error message list:
1: 严重性	代码	说明	项目	文件	行	禁止显示状态
错误	LNK2001	无法解析的外部符号 __stdio_common_vswprintf	rpiq	C:\Users\Administrator\Desktop\windows-drivers\drivers\mailbox\bcm2836\device.obj	1	

2:严重性	代码	说明	项目	文件	行	禁止显示状态
错误	LNK1120	1 个无法解析的外部命令	rpiq	C:\Users\Administrator\Desktop\windows-drivers\build\bcm2836\ARM64\Release\Output\rpiq.sys	1	

image: 
![image](https://user-images.githubusercontent.com/20411721/120281520-a10cb600-c2eb-11eb-8aed-d32095bd43ff.png)

"vcos_win32_kern_generic" driver project：I also disable the 'Spectre' of 'vcos_win32_kern_generic', However, other errors are displayed after disabling. This error should be an error during link.
error message list:
1：严重性	代码	说明	项目	文件	行	禁止显示状态
错误	C2011	“timespec”:“struct”类型重定义	vcos_win32_kern_generic	C:\Users\Administrator\Desktop\windows-drivers\drivers\misc\userland\interface\vcos\win32\vcos_platform.h	139	
![image](https://user-images.githubusercontent.com/20411721/120282041-458ef800-c2ec-11eb-807e-29804e643ce0.png)

I tried to delete this structure, but I couldn't solve it。
![image](https://user-images.githubusercontent.com/20411721/120282218-77a05a00-c2ec-11eb-88f0-84a7d28e33f4.png)
![image](https://user-images.githubusercontent.com/20411721/120282280-8424b280-c2ec-11eb-99c3-55ac72ba2222.png)

**Comment by mariobalanica** [comment]
Thanks for reporting this. CI builds were also failing.

I've pushed a partial fix here: https://github.com/raspberrypi/windows-drivers/commit/e053007032538b647f9b73f565d3b6ba6bcd9baf 

It's partial because of the stdio workaround, so I'll keep this issue open until there's a proper fix available.

**Comment by 527395632** [comment]
Thank you very much for the help of @mariobalanica. I will continue to follow up on this issue. Today, I'm re re installing the environment. I'm still wondering if it's my development environment configuration. I'll try to compile it after I install it

**Comment by mariobalanica** [comment]
You should be able to compile all the drivers now.

**Comment by 527395632** [comment]
Yes, now the 2004 version of the SDK can be compiled and passed. I'll see if the 1809 version of the SDK can be compiled and passed. I'll send the test results later

**Comment by mariobalanica** [comment]
Reverted the workarounds as they're not required anymore: a8398a59e5c46a9e576f250b177bff097e33545a
