### ISSUE TITLE
driver issue

### ISSUE THREAD

**Issue by gameyboy11** [raspberrypi/windows-drivers#41]
I tried using the drivers
[windows-drivers-master (1).zip](https://github.com/raspberrypi/windows-drivers/files/7780595/windows-drivers-master.1.zip)
but every time I used the WoR flasher it just kept saying installation failed after getting to the installing drivers screen.

**Comment by gameyboy11** [comment]
forgot to say it was using windows 11 version 22523

**Comment by mariobalanica** [comment]
WoR-Flasher downloads everything needed automatically, you don't have to select any ZIP archive.
